name: Python 3.7

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Python 3.7
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Registry Auth
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Python 3.7
        uses: docker/build-push-action@v2
        with:
          context: python/3.7
          file: python/3.7/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/binkhq/python:3.7

      - name: Build and Push Pyo 3.7
        uses: docker/build-push-action@v2
        with:
          context: python/3.7-pyo3
          file: python/3.7-pyo3/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/binkhq/python:3.7-pyo3
